apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}
  labels:
    app: {{.Release.Name}}
spec:
  strategy:
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: {{.Release.Name}}
  template:
    metadata:
      annotations:
        timestamp: {{now}}
      labels:
        app: {{.Release.Name}}
    spec:
      containers:
        - name: {{.Release.Name}}
          image: {{ required "A valid .Values.service.image entry required!" .Values.service.image }}:{{ required "A valid .Values.service.version entry required!" .Values.service.version }}
          volumeMounts:
            - mountPath: /config
              name: config-volume
          ports:
          {{ range .Values.service.ports }}
            - containerPort: {{ . }}
          {{ end }}
      volumes:
        - name: config-volume
          configMap:
            name: {{.Release.Name}}-configmap
            items:
              - key: application.properties
                path: application.properties