apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}
spec:
  type: LoadBalancer
  selector:
    app: {{.Release.Name}}
  ports:
  {{ range .Values.service.ports }}
    - name: port-{{.}}
      protocol: TCP
      port: {{ . }}
      targetPort: {{ . }}
  {{ end }}