apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}
  labels:
    app: {{.Release.Name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Release.Name}}
  template:
    metadata:
      labels:
        app: {{.Release.Name}}
    spec:
      containers:
        - name: {{.Release.Name}}
          image: {{ required "A valid .Values.service.image entry required!" .Values.service.image }}:{{ required "A valid .Values.service.version entry required!" .Values.service.version }}
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{.Release.Name}}-secret
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{.Release.Name}}-secret
                  key: password
          ports:
            - containerPort: {{ required "A valid .Values.service.port entry required!" .Values.service.port }}