apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
data:
  username: {{.Files.Get "secrets/username.conf" | b64enc}}
  password: {{.Files.Get "secrets/password.conf" | b64enc}}